#!/bin/sh
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
HAS_IPV6="$SCRIPT_DIR/../has_ipv6"

# Flush the security table.
iptables -t security -F
iptables -t security -X NEWCONN 2>/dev/null
if "$HAS_IPV6"; then
ip6tables -t security -F
ip6tables -t security -X NEWCONN 2>/dev/null
fi
