#!/usr/bin/perl
use Test::More;
use File::Basename qw(dirname basename);

BEGIN {
    $basedir = dirname($0);
    $basedir = `cd $basedir && pwd`;
    chomp($basedir);
    $proto = basename($basedir);

    if ( $proto eq "tcp" or $proto eq "mptcp" ) {
        if ( $proto eq "mptcp" && system("modprobe mptcp 2>/dev/null") ne 0 ) {
            plan skip_all => "protocol mptcp not supported";
        }
        $is_stream   = 1;
        $fail_value1 = 5;
        $fail_value2 = 5;
        $test_count  = 19;
    }
    elsif ( $proto eq "udp" ) {
        $is_stream   = 0;
        $fail_value1 = 9;
        $fail_value2 = 8;
        $test_count  = 11;
    }
    else {
        plan skip_all => "unknown protocol name \'$proto\'";
    }

    $test_ipsec = 0;
    if ( system("ip xfrm policy help 2>&1 | grep -q ctx") eq 0 ) {
        $test_count += 4;
        $test_ipsec = 1;
    }

    # Determine if CALIPSO supported by netlabelctl(8) and kernel.
    $test_calipso = 0;
    $netlabelctl  = `netlabelctl -V`;
    $netlabelctl =~ s/\D//g;
    $kvercur = `uname -r`;
    chomp($kvercur);

    $rc = `$basedir/../kvercmp $kvercur 4.8`;
    if ( $netlabelctl gt "021" and $rc > 0 ) {
        $test_count += $is_stream ? 3 : 2;
        $test_calipso = 1;
    }

    # Determine if kernel has legacy iptables support
    $test_iptables = 0;

    $rc = system("modprobe ip_tables 2>/dev/null");
    if ( $rc == 0 ) {
        $test_count += 4;
        $test_iptables = 1;
    }

    # Determine if nftables has secmark support
    $test_nft = 0;

    $rc = system("nft -c -f $basedir/nftables-load 2>/dev/null");
    if ( $rc == 0 ) {
        $test_count += 4;
        $test_nft = 1;
    }

    plan tests => $test_count;
}

sub server_start {
    my ( $runcon_args, $args ) = @_;
    my $pid;

    system("mkfifo $basedir/flag");

    if ( ( $pid = fork() ) == 0 ) {
        exec "runcon $runcon_args $basedir/server -f $basedir/flag $args";
    }

    # Wait for it to initialize.
    open( my $f, "<", "$basedir/flag" );
    my $rin = '';
    vec( $rin, fileno($f), 1 ) = 1;
    select( $rin, undef, undef, 5 );
    close($f);
    return $pid;
}

sub server_end {
    my ($pid) = @_;

    kill KILL, $pid;
    waitpid $pid, 0;
    system("rm -f $basedir/flag");
}

# Load NetLabel configuration for full CIPSO/IPv4 labeling over loopback.
system "/bin/sh $basedir/cipso-fl-load";

# Start the server.
$pid = server_start( "-t test_inet_server_t", "$proto 65535" );

# Verify that authorized client can communicate with the server.
$result =
  system "runcon -t test_inet_client_t $basedir/client $proto 127.0.0.1 65535";
ok( $result eq 0 );

# Verify that unauthorized client cannot communicate with the server.
$result = system
"runcon -t test_inet_bad_client_t -- $basedir/client $proto 127.0.0.1 65535 2>&1";
ok( $result >> 8 eq $fail_value1 );

# Kill the server.
server_end($pid);

# Flush NetLabel configuration.
system "/bin/sh $basedir/cipso-fl-flush";

# Load NetLabel configuration for CIPSO/IPv4 using TAG 1 over loopback.
system "/bin/sh $basedir/cipso-load-t1";

if ($is_stream) {

    # Start the server with a defined level.
    $pid =
      server_start( "-t test_inet_server_t -l s0:c20.c250", "$proto 65535" );

# Verify that authorized client can communicate with the server using level within T1 range.
    $result = system
"runcon -t test_inet_client_t -l s0:c61.c239 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c61.c239 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

# Verify that authorized client cannot communicate with the server using different level.
    $result = system
"runcon -t test_inet_client_t -l s0:c19,c120 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

# TAG 1 allows categories 0 to 239 to be sent, if greater then ENOSPC (No space left on device)
    $result = system
"runcon -t test_inet_client_t -l s0:c0.c240 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

    # Kill the server.
    server_end($pid);
}
else {
    # Start the server with a defined level.
    $pid =
      server_start( "-t test_inet_server_t -l s0:c20.c50", "$proto 65535" );

# Verify that authorized client can communicate with the server using same levels.
    $result = system
"runcon -t test_inet_client_t -l s0:c20.c50 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c20.c50 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

# Verify that authorized client cannot communicate with the server using levels dominating the server.
    $result = system
"runcon -t test_inet_client_t -l s0:c40.c51 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

    # Kill the server.
    server_end($pid);
}

# Flush NetLabel configuration.
system "/bin/sh $basedir/cipso-flush";

# Load NetLabel configuration for CIPSO/IPv4 using TAG 2 over loopback.
system "/bin/sh $basedir/cipso-load-t2";

if ($is_stream) {

    # Start the server with a defined level.
    $pid =
      server_start( "-t test_inet_server_t -l s0:c0.c100", "$proto 65535" );

    # Verify that authorized client can communicate with the server using level.
    $result = system
"runcon -t test_inet_client_t -l s0:c90.c100 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c90.c100 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

    # Verify that authorized client can communicate with the server using level.
    $result = system
"runcon -t test_inet_client_t -l s0:c0.c14 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c0.c14 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

# Verify that authorized client cannot communicate with the server using different level.
    $result = system
"runcon -t test_inet_client_t -l s0:c101 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

# TAG 2 allows a maximum of 15 categories in exchange, if greater then ENOSPC (No space left on device)
    $result = system
"runcon -t test_inet_client_t -l s0:c0.c16 -- $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

    # Kill the server.
    server_end($pid);
}
else {
    # Start the server with a defined level.
    $pid = server_start( "-t test_inet_server_t -l s0:c0.c14", "$proto 65535" );

# Verify that authorized client can communicate with the server using same levels.
    $result = system
"runcon -t test_inet_client_t -l s0:c0.c14 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c0.c14 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

# Verify that authorized client cannot communicate with the server using levels dominating the server.
    $result = system
"runcon -t test_inet_client_t -l s0:c15 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

    # Kill the server.
    server_end($pid);
}

# Flush NetLabel configuration.
system "/bin/sh $basedir/cipso-flush";

# Load NetLabel configuration for CIPSO/IPv4 using TAG 5 over loopback.
# TAG 5 allows a maximum of 7 ranges in exchange, if greater then ENOSPC (No space left on device), however
# note from kernel net/ipv4/cipso_ipv4.c comments:
# * You may note that the IETF draft states that the maximum number
# * of category ranges is 7, but if the low end of the last category range is
# * zero then it is possible to fit 8 category ranges because the zero should
# * be omitted. */
system "/bin/sh $basedir/cipso-load-t5";

# Start the server with a defined level.
$pid = server_start( "-t test_inet_server_t -l s0:c0.c100", "$proto 65535" );

# Verify that authorized client can communicate with the server using level.
$result = system
"runcon -t test_inet_client_t -l s0:c0.c100 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c0.c100 $proto 127.0.0.1 65535";
ok( $result eq 0 );

if ($is_stream) {

    # Verify that authorized client can communicate with the server using level.
    $result = system
"runcon -t test_inet_client_t -l s0:c8.c100 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c8.c100 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

# Verify that authorized client cannot communicate with the server using different level.
    $result = system
"runcon -t test_inet_client_t -l s0:c8.c101 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );

    # Verify ok with the 8 entries when cat c0:
    $result = system
"runcon -t test_inet_client_t -l s0:c0.c3,c20.c25,c30.c36,c40.c45,c50.c55,c60.c66,c70.c78,c80.c88 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c0.c3,c20.c25,c30.c36,c40.c45,c50.c55,c60.c66,c70.c78,c80.c88 $proto 127.0.0.1 65535";
    ok( $result eq 0 );

    # Verify fail with the 8 entries when cat !c0:
    $result = system
"runcon -t test_inet_client_t -l s0:c20.c25,c30.c36,c40.c45,c50.c55,c60.c66,c70.c78,c80.c88,c90.c99 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );
}
else {
# Verify that authorized client cannot communicate with the server using levels dominating the server.
    $result = system
"runcon -t test_inet_client_t -l s0:c40.c101 $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value1 );
}

# Kill the server.
server_end($pid);

# Flush NetLabel configuration.
system "/bin/sh $basedir/cipso-flush";

# Verify that authorized domain can bind.
$result =
  system "runcon -t test_inet_bind_t -- $basedir/bind $proto 65535 2>&1";
ok( $result eq 0 );

# Verify that domain without name_bind cannot bind.
$result =
  system
  "runcon -t test_inet_no_name_bind_t -- $basedir/bind $proto 65535 2>&1";
ok($result);

# Verify that domain without node_bind cannot bind.
$result =
  system
  "runcon -t test_inet_no_node_bind_t -- $basedir/bind $proto 65535 2>&1";
ok($result);

if ($is_stream) {

    # Verify that authorized domain can connect to TCP socket.
    $result = system
      "runcon -t test_inet_connect_t -- $basedir/connect $proto 65535 2>&1";
    ok( $result eq 0 );

    # Verify that domain without name_connect cannot connect to TCP socket.
    $result =
      system
"runcon -t test_inet_no_name_connect_t -- $basedir/connect $proto 65535 2>&1";
    ok($result);
}

if ($test_ipsec) {

    # Load IPSEC configuration.
    system "/bin/sh $basedir/ipsec-load";

    # Start the server.
    $pid = server_start( "-t test_inet_server_t", "$proto 65535" );

    # Verify that authorized client can communicate with the server.
    $result =
      system
      "runcon -t test_inet_client_t $basedir/client $proto 127.0.0.1 65535";
    ok( $result eq 0 );

    # Verify that unauthorized client cannot communicate with the server.
    $result = system
"runcon -t test_inet_bad_client_t -- $basedir/client $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value2 );

    if ($is_stream) {

        # Verify that authorized client can communicate with the server.
        $result =
          system
          "runcon -t test_inet_client_t $basedir/client $proto ::1 65535";
        ok( $result eq 0 );
    }

    # Verify that unauthorized client cannot communicate with the server.
    $result = system
"runcon -t test_inet_bad_client_t -- $basedir/client $proto ::1 65535 2>&1";
    ok( $result >> 8 eq $fail_value2 );

    # Kill the server.
    server_end($pid);

    if ( not $is_stream ) {

   # Start the server for IPSEC test using IPv6 but do not request peer context.
        $pid = server_start( "-t test_inet_server_t", "-n $proto 65535" );

        # This test now passes.
        $result = system
"runcon -t test_inet_client_t $basedir/client -e nopeer $proto ::1 65535";
        ok( $result eq 0 );

        # Kill the server.
        server_end($pid);
    }

    # Flush IPSEC configuration.
    system "/bin/sh $basedir/ipsec-flush";
}

#
################## Test iptables/nftables configuration ######################
#
sub test_tables {

    # Start the server.
    $pid = server_start( "-t test_inet_server_t", "-n $proto 65535" );

    # Verify that authorized client can communicate with the server.
    $result = system
"runcon -t test_inet_client_t -- $basedir/client -e nopeer $proto 127.0.0.1 65535";
    ok( $result eq 0 );

    # Verify that unauthorized client cannot communicate with the server.
    $result = system
"runcon -t test_inet_bad_client_t -- $basedir/client -e nopeer $proto 127.0.0.1 65535 2>&1";
    ok( $result >> 8 eq $fail_value2 );

    # Verify that authorized client can communicate with the server.
    $result = system
"runcon -t test_inet_client_t -- $basedir/client -e nopeer $proto ::1 65535";
    ok( $result eq 0 );

    # Verify that unauthorized client cannot communicate with the server.
    $result = system
"runcon -t test_inet_bad_client_t -- $basedir/client -e nopeer $proto ::1 65535 2>&1";
    ok( $result >> 8 eq $fail_value2 );

    # Kill the server.
    server_end($pid);
}

if ($test_iptables) {
    print "Testing iptables (IPv4/IPv6).\n";
    system "/bin/sh $basedir/iptables-load";
    test_tables();
    system "/bin/sh $basedir/iptables-flush";
}

if ($test_nft) {
    print "Testing nftables (IPv4/IPv6).\n";
    system "nft -f $basedir/nftables-load";
    test_tables();
    system "nft -f $basedir/nftables-flush";
}

if ($test_calipso) {

    # Load NetLabel configuration for CALIPSO/IPv6 labeling over loopback.
    system "/bin/sh $basedir/calipso-load";

    if ($is_stream) {

        # Start the server.
        $pid =
          server_start( "-t test_inet_server_t -l s0:c0.c10", "$proto 65535" );

        # Verify that authorized client can communicate with the server.
        $result = system
"runcon -t test_inet_client_t -l s0:c0.c10 $basedir/client -e system_u:object_r:netlabel_peer_t:s0:c0.c10 $proto ::1 65535";
        ok( $result eq 0 );

# Verify that authorized client can communicate with the server using different valid level.
        $result = system
"runcon -t test_inet_client_t -l s0:c8.c10 $basedir/client -e  system_u:object_r:netlabel_peer_t:s0:c8.c10 $proto ::1 65535";
        ok( $result eq 0 );
    }
    else {
        # IPv6 currently doesn't support getting the packet context
        # via CMSG (https://github.com/SELinuxProject/selinux-kernel/issues/24)
        # so don't check the returned label here.

        # Start the server.
        $pid = server_start( "-t test_inet_server_t -l s0:c0.c10",
            "-n $proto 65535" );

        # Verify that authorized client can communicate with the server.
        $result = system
"runcon -t test_inet_client_t -l s0:c0.c10 $basedir/client -e nopeer $proto ::1 65535";
        ok( $result eq 0 );
    }

# Verify that authorized client cannot communicate with the server using invalid level.
    $result = system
"runcon -t test_inet_client_t -l s0:c8.c12 -- $basedir/client $proto ::1 65535 2>&1";
    ok( $result >> 8 eq $fail_value2 );

    # Kill the server.
    server_end($pid);

    system "/bin/sh $basedir/calipso-flush";
}

exit;
