#!/usr/bin/perl

use Test;
BEGIN { plan tests => 2 }

$basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

system("cp /bin/true $basedir/true");

# Verify that test_entrypoint_t cannot be entered via test_entrypoint_deny_t.
system("chcon -t test_entrypoint_deny_t $basedir/true");
$result = system("runcon -t test_entrypoint_t $basedir/true 2>&1");
ok($result);    #this should fail

# Verify that test_entrypoint_t can be entered via test_entrypoint_allow_t.
system("chcon -t test_entrypoint_allow_t $basedir/true");
$result = system("runcon -t test_entrypoint_t $basedir/true");
ok( $result, 0 );    #this should pass

# Cleanup.
system("rm -f $basedir/true");

exit;
