#!/usr/bin/perl
#
# This test exercises the netlink extended perms support
#

use Test;

BEGIN {
    $test_count = 2;
    plan tests => $test_count;
}

$basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

#
# Attempt to send the netlink messages from the allowed domain.
#
$result = system "runcon -t test_nlmsg_xperm_t -- $basedir/nlmsg 2>&1";
ok( $result, 0 );

#
# Attempt to send the netlink messages from the not-allowed domain.
#
$result = system "runcon -t test_nlmsg_noxperm_t -- $basedir/nlmsg 2>&1";
ok($result);

exit;
