#!/usr/bin/perl

use Test::More;

my %conf;

BEGIN {
    $basedir = $0;
    $basedir =~ s|(.*)/[^/]*|$1|;

    $confpath = $basedir . "/ibendport_test.conf";
    open( $f, $confpath ) or die("Couldn't open $confpath");
    while ( $r = <$f> ) {
        if ( $r =~ /^\s*#/ || $r =~ /^\s*$/ ) { next; }
        chomp $r;
        ( $k, $v ) = split( /=/, $r );
        $conf{$k} = $v;
    }
    close($f);

    # Verify that we really want to run these tests.
    if ( $conf{SELINUX_INFINIBAND_ENDPORT_TEST} eq 1 ) {
        plan tests => 2;
    }
    else {
        plan skip_all => "test not configured";
    }
}

@allowed_device_port =
  split( /,/, $conf{SELINUX_INFINIBAND_ENDPORT_TEST_ALLOWED} );
@denied_device_port =
  split( /,/, $conf{SELINUX_INFINIBAND_ENDPORT_TEST_DENIED} );

foreach (@allowed_device_port) {
    @dev_port_pair = split( / /, $_ );

    system "semanage ibendport -a -t test_ibendport_t -z $_ 2>/dev/null";
    $result = system
"runcon -t test_ibendport_manage_subnet_t smpquery PKeyTable -C $dev_port_pair[0] -P $dev_port_pair[1] -D 1 2>/dev/null";
    system "semanage ibendport -d -t test_ibendport_t -z $_ 2>/dev/null";
    if ( $result ne 0 ) {
        last;
    }
}
ok( $result eq 0 );

foreach (@denied_device_port) {
    @dev_port_pair = split( / /, $_ );
    $result        = system
"runcon -t test_ibendport_manage_subnet_t smpquery PKeyTable -C $dev_port_pair[0] -P $dev_port_pair[1] -D 1 2>/dev/null";

    if ( $result >> 8 eq 0 ) {
        last;
    }
}

ok( int( $result >> 8 ) ne 0 );

exit;
