#!/usr/bin/perl

use Test;
BEGIN { plan tests => 2 }

my $ret;

# Older systems use /sys/fs/cgroup/unified, newer use /sys/fs/cgroup.
my $dir;
if ( -d "/sys/fs/cgroup/unified" ) {
    $dir = "/sys/fs/cgroup/unified/selinuxtest";
}
else {
    $dir = "/sys/fs/cgroup/selinuxtest";
}

# Create a new cgroupfs directory and relabel it.
mkdir("$dir");
system("chcon -R -t test_cgroup_t $dir");

# Create a subdirectory in it.
mkdir("$dir/subdir");

$ret = system("secon -tf $dir/subdir | grep -q '^test_cgroup_t\$'");
ok( $ret, 0 );    # Did the subdirectory inherit the parent's label?

$ret = system("secon -tf $dir/subdir/cgroup.type | grep -q '^test_cgroup_t\$'");
ok( $ret, 0 );    # Did also files in the subdirectory inherit the label?

# Cleanup.
rmdir("$dir/subdir");
rmdir("$dir");

exit;
