#!/bin/sh

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
HAS_IPV6="$SCRIPT_DIR/../has_ipv6"

netlabelctl map del default
netlabelctl map add default address:0.0.0.0/0 protocol:unlbl
if "$HAS_IPV6"; then
netlabelctl map add default address:::/0 protocol:unlbl
fi
netlabelctl unlbl add interface:lo address:127.0.0.0/8 label:system_u:object_r:netlabel_sctp_peer_t:s0
if "$HAS_IPV6"; then
netlabelctl unlbl add interface:lo address:::1/128 label:system_u:object_r:netlabel_sctp_peer_t:s0
fi
#netlabelctl -p unlbl list
