#!/usr/bin/perl

use Test;
BEGIN { plan tests => 2}

$basedir = $0;  $basedir =~ s|(.*)/[^/]*|$1|;

# Verify that test_setpgid_yes_t can setpgid.
$result = system ("runcon -t test_setpgid_yes_t -- $basedir/source 2>&1");
ok($result, 0);

# Verify that test_setpgid_no_t cannot setpgid.
$result = system ("runcon -t test_setpgid_no_t -- $basedir/source 2>&1");
ok($result);

exit;

