#!/usr/bin/perl

use Test;
BEGIN { plan tests => 4 }

# task_getpgid, but all permissions are assigned using attributes (two step transition)

$basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

# Verify that test_setpgid_yes_t can setpgid.
$result =
  system("runcon -t test_attribute_setpgid_yes_t -- $basedir/source 2>&1");
ok( $result, 0 );

# Verify that test_setpgid_no_t cannot setpgid.
$result =
  system("runcon -t test_attribute_setpgid_no_t -- $basedir/source 2>&1");
ok($result);

# entrypoint test, but all permissions are passed using attributes

$basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

system("cp /bin/true $basedir/true");

# Verify that test_attribute_domain_t cannot be entered via test_attribute_entrypoint_deny_t.
system("chcon -t test_attribute_entrypoint_deny_t $basedir/true");
$result = system("runcon -t test_attribute_domain_t $basedir/true 2>&1");
ok($result);    #this should fail

# Verify that test_attribute_domain_t can be entered via test_attribute_entrypoint_t.
system("chcon -t test_attribute_entrypoint_t $basedir/true");
$result = system("runcon -t test_attribute_domain_t $basedir/true");
ok( $result, 0 );    #this should pass

# Cleanup.
system("rm -f $basedir/true");

exit;

